'use strict';

const { getStore } = require('@netlify/blobs');

const STORE_NAME = 'widget-uploads';
// Keys are only ever generated by widget-image-upload.js in this exact
// shape, so a strict match doubles as an allowlist against path traversal
// or someone probing the store with an arbitrary key.
const KEY_PATTERN = /^[0-9]+-[0-9a-f]{16}\.(png|jpe?g|webp|gif)$/i;

exports.handler = async function handler(event) {
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 204,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
      },
      body: '',
    };
  }

  if (event.httpMethod !== 'GET') {
    return { statusCode: 405, body: 'Method not allowed.' };
  }

  const key = String((event.queryStringParameters || {}).key || '');
  if (!KEY_PATTERN.test(key)) {
    return { statusCode: 400, body: 'Invalid image key.' };
  }

  try {
    const store = getStore({ name: STORE_NAME, consistency: 'strong' });
    const entry = await store.getWithMetadata(key, { type: 'arrayBuffer' });
    if (!entry || !entry.data) {
      return { statusCode: 404, body: 'Image not found.' };
    }

    const contentType = entry.metadata?.contentType || 'application/octet-stream';
    return {
      statusCode: 200,
      headers: {
        'Content-Type': contentType,
        // Keys are unique per upload and never reused, so a cached copy is
        // always valid for that key's lifetime.
        'Cache-Control': 'public, max-age=31536000, immutable',
        'Access-Control-Allow-Origin': '*',
      },
      body: Buffer.from(entry.data).toString('base64'),
      isBase64Encoded: true,
    };
  } catch (error) {
    return { statusCode: 500, body: 'Could not load image.' };
  }
};
